//Auth actions
export const CLEAR_ERROR = 'CLEAR_ERROR'
export const SENDING_REQUEST = 'SENDING_REQUEST'
export const REQUEST_ERROR = 'REQUEST_ERROR'
export const LOGOUT = 'LOGOUT'
export const USERDATA_REQUEST = 'USERDATA_REQUEST'
export const UPDATE_USERDATA = 'UPDATE_USERDATA'
export const UPDATE_USERDATA_TOPICSAVED = 'UPDATE_USERDATA_TOPICSAVED'
