//Auth actions
export const CLEAR_ERROR = 'CLEAR_ERROR'
export const SENDING_REQUEST = 'SENDING_REQUEST'
export const REQUEST_ERROR = 'REQUEST_ERROR'
export const LOGOUT = 'LOGOUT'
export const NEWTOPIC_SUBMIT = 'NEWTOPIC_SUBMIT'
export const NEWCONTENT_SUBMIT = 'NEWCONTENT_SUBMIT'
export const SUBMIT_CONTENT = 'SUBMIT_CONTENT'
export const UPDATE_TOPIC = 'UPDATE_TOPIC'
